### PR TITLE
Update api-catalog-cli version from `1.1.0` to `1.1.2` and grep search for success message so we can return error otherwise

### PR DESCRIPTION
**Pull request by liamstevens111**
## What happened 👀

1. Updated version (didn't notice any difference)
2. `grep` search for success message, if doesn't exist then `exit 1` (return error)

https://docs.mulesoft.com/release-notes/api-catalog/api-catalog-release-notes

Screenshot 2024-09-19 at 10 17 26

## Insight 📝

`N/A`

## Proof Of Work 📹

Tested on:
- https://github.com/Jollibee-Foods-Corporation/jfc-global-exp-api-doc/pull/355

Failure (path incorrect):

https://github.com/Jollibee-Foods-Corporation/jfc-global-exp-api-doc/actions/runs/10952458848/job/30411172060

Screenshot 2024-09-20 at 10 09 35

Success:

https://github.com/Jollibee-Foods-Corporation/jfc-global-exp-api-doc/actions/runs/10952513309/job/30411320471

Screenshot 2024-09-20 at 10 14 42

### CODE REVIEW

**Comment by liamstevens111** [comment]
No JIRA task created or referenced, just POW of some error checking here.

**Review by automch-code — APPROVED** [review]
LGTM 🚀

**Review by toby-thanathip — APPROVED** [review]
Cool, nice job 💪

**Review by andyduong1920 — APPROVED** [review]

**Comment by andyduong1920** [comment]
Thanks @liamstevens111 - I will brings this new version to app docs repo - will let you know the PRs list soon cc @toby-thanathip

**Pull request merged**
